"""Add morning and evening reminder time

Revision ID: 528a734a4e7b
Revises: f2e459068aad
Create Date: 2026-07-28 18:05:10.744707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528a734a4e7b'
down_revision = 'f2e459068aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_time_evening', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email_time_morning', sa.String(), nullable=True))
        batch_op.drop_column('email_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_time', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('email_time_morning')
        batch_op.drop_column('email_time_evening')

    # ### end Alembic commands ###
