"""registration changed

Revision ID: 5ffbda4c42f6
Revises: b27c342412f5
Create Date: 2026-08-23 19:56:39.528789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffbda4c42f6'
down_revision = 'b27c342412f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_completed', sa.Boolean(), nullable=True))
        batch_op.drop_column('registered')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('registration_completed')

    # ### end Alembic commands ###
