"""add shift reminder sent tracking columns

Revision ID: 62c7ebde987b
Revises: 88b7acf4b089
Create Date: 2026-09-18 11:40:13.400674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c7ebde987b'
down_revision = '88b7acf4b089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_reminder_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shift_reminder_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_column('shift_reminder_sent_at')
        batch_op.drop_column('daily_reminder_sent_at')

    # ### end Alembic commands ###
