"""add reminder settings and sent tracking

Revision ID: 88b7acf4b089
Revises: b839f3faccc1
Create Date: 2026-09-05 08:07:17.349392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b7acf4b089'
down_revision = 'b839f3faccc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('daily_reminder_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('daily_reminder_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
