"""neues datenmodell

Revision ID: 8fd4f9205baf
Revises: 528a734a4e7b
Create Date: 2026-08-22 20:45:07.306954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd4f9205baf'
down_revision = '528a734a4e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('invite_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('mail', sa.String(length=100), nullable=True),
    sa.Column('mail_verified', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('registered', sa.Boolean(), nullable=True),
    sa.Column('time_zone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('shift_type', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("DROP TABLE IF EXISTS register CASCADE")
    op.drop_table('date')
    op.drop_table('verification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification',
    sa.Column('user_verification_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('user_token', sa.VARCHAR(), nullable=True),
    sa.Column('user_token_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['register.user_id'], ),
    sa.PrimaryKeyConstraint('user_verification_id')
    )
    op.create_table('date',
    sa.Column('date_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.VARCHAR(length=10), nullable=True),
    sa.Column('time_begin', sa.VARCHAR(length=12), nullable=True),
    sa.Column('time_end', sa.VARCHAR(length=12), nullable=True),
    sa.Column('free', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['register.user_id'], ),
    sa.PrimaryKeyConstraint('date_id')
    )
    op.create_table('register',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('user_mail', sa.VARCHAR(length=100), nullable=True),
    sa.Column('user_verification', sa.BOOLEAN(), nullable=True),
    sa.Column('user_password_hash', sa.VARCHAR(), nullable=True),
    sa.Column('user_locked_until', sa.DATETIME(), nullable=True),
    sa.Column('user_trys', sa.INTEGER(), nullable=True),
    sa.Column('user_city', sa.VARCHAR(), nullable=True),
    sa.Column('user_registered', sa.BOOLEAN(), nullable=True),
    sa.Column('first_mail_send', sa.VARCHAR(), nullable=True),
    sa.Column('second_mail_send', sa.VARCHAR(), nullable=True),
    sa.Column('user_time_zone', sa.INTEGER(), nullable=True),
    sa.Column('email_time_evening', sa.VARCHAR(), nullable=True),
    sa.Column('email_time_morning', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_mail'),
    sa.UniqueConstraint('user_name')
    )
    op.drop_table('team_member')
    op.drop_table('shift')
    op.drop_table('user')
    op.drop_table('team')
    # ### end Alembic commands ###
