"""initial migration

Revision ID: 987756720cd4
Revises: 
Create Date: 2026-07-24 20:17:48.437065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987756720cd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=40), nullable=True),
    sa.Column('user_mail', sa.String(length=100), nullable=True),
    sa.Column('user_verification', sa.Boolean(), nullable=True),
    sa.Column('user_password_hash', sa.String(), nullable=True),
    sa.Column('user_locked_until', sa.DateTime(), nullable=True),
    sa.Column('user_trys', sa.Integer(), nullable=True),
    sa.Column('user_city', sa.String(), nullable=True),
    sa.Column('email_time', sa.String(), nullable=True),
    sa.Column('user_registered', sa.Boolean(), nullable=True),
    sa.Column('first_mail_send', sa.String(), nullable=True),
    sa.Column('second_mail_send', sa.String(), nullable=True),
    sa.Column('user_time_zone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_mail'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('date',
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('time_begin', sa.String(length=12), nullable=True),
    sa.Column('time_end', sa.String(length=12), nullable=True),
    sa.Column('free', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['register.user_id'], ),
    sa.PrimaryKeyConstraint('date_id')
    )
    op.create_table('verification',
    sa.Column('user_verification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['register.user_id'], ),
    sa.PrimaryKeyConstraint('user_verification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification')
    op.drop_table('date')
    op.drop_table('register')
    # ### end Alembic commands ###
