"""Transfered daily_reminder_sent_at to User

Revision ID: b927468cc27a
Revises: 62c7ebde987b
Create Date: 2026-09-24 20:01:34.954088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b927468cc27a'
down_revision = '62c7ebde987b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_column('daily_reminder_sent_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_reminder_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('daily_reminder_sent_at')

    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_reminder_sent_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
