"""add new class Base

Revision ID: e1fffd707d8f
Revises: 5ffbda4c42f6
Create Date: 2026-08-29 12:40:59.926823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fffd707d8f'
down_revision = '5ffbda4c42f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_shift")
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('shift_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('invite_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        

    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('joined_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('mail',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('mail_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('registration_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        

    with op.batch_alter_table('verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('token_date', sa.DateTime(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('user_token')
        batch_op.drop_column('user_token_date')

    op.execute('ALTER TABLE team DROP CONSTRAINT IF EXISTS uq_team_invite_code')
    op.execute('ALTER TABLE team ADD CONSTRAINT uq_team_invite_code UNIQUE (invite_code)')
    op.execute('ALTER TABLE team DROP CONSTRAINT IF EXISTS uq_team_name')
    op.execute('ALTER TABLE team ADD CONSTRAINT uq_team_name UNIQUE (name)')
    op.execute('ALTER TABLE "user" DROP CONSTRAINT IF EXISTS uq_user_mail')
    op.execute('ALTER TABLE "user" ADD CONSTRAINT uq_user_mail UNIQUE (mail)')
    op.execute('ALTER TABLE "user" DROP CONSTRAINT IF EXISTS uq_user_name')
    op.execute('ALTER TABLE "user" ADD CONSTRAINT uq_user_name UNIQUE (name)')
    op.execute('ALTER TABLE verification DROP CONSTRAINT IF EXISTS uq_verification_token')
    op.execute('ALTER TABLE verification ADD CONSTRAINT uq_verification_token UNIQUE (token)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_token_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('user_token', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_verification_token'), type_='unique')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('token_date')
        batch_op.drop_column('token')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_mail'), type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('registration_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mail_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('mail',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)

    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.alter_column('joined_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_team_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_team_invite_code'), type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('invite_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('shift_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_shift',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=True),
    sa.Column('start', sa.DATETIME(), nullable=True),
    sa.Column('end', sa.DATETIME(), nullable=True),
    sa.Column('shift_type', sa.VARCHAR(), nullable=False),
    sa.Column('note', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
