"""add token date

Revision ID: f2e459068aad
Revises: 987756720cd4
Create Date: 2026-07-26 10:30:35.582655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e459068aad'
down_revision = '987756720cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_token_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification', schema=None) as batch_op:
        batch_op.drop_column('user_token_date')

    # ### end Alembic commands ###
